spring.application.name=api
# <1>
#spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:9090
# <2>
server.port=8080
#

#
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.integration=DEBUG
#
spring.security.oauth2.client.provider.spring.issuer-uri=http://localhost:9090
spring.security.oauth2.client.registration.crm.provider=spring
spring.security.oauth2.client.registration.crm.client-id=crm
spring.security.oauth2.client.registration.crm.client-secret=crm
spring.security.oauth2.client.registration.crm.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.crm.client-authentication-method=client_secret_basic
spring.security.oauth2.client.registration.crm.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}
spring.security.oauth2.client.registration.crm.scope=openid,profile

spring.rabbitmq.username=user
spring.rabbitmq.password=password
